ROBOT:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      link_01_name__link_02_name:
        type: effort_controllers/JointPositionController
        joint: link_01_name__link_02_name
        pid: {p: 10.0, i: 0.0, d: 1.0}
      link_02_name__link_03_name:
        type: effort_controllers/JointPositionController
        joint: link_02_name__link_03_name
        pid: {p: 5.0, i: 2.0, d: 1.0}
